apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blog
  labels:
    app: django-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-blog
  template:
    metadata:
      labels:
        app: django-blog
    spec:
      containers:
      - name: django-blog
        image: arshia2562/django-blog:1.3
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: database_username
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: blog-secret
              key: database_password
        - name: POSTGRES_NAME
          valueFrom: 
            configMapKeyRef:
              name: blog-configmap
              key: database_name
        - name: POSTGRES_HOST
          valueFrom: 
            configMapKeyRef:
              name: blog-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: django-blog-service
spec:
  selector:
    app: django-blog
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
