apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.2
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /data/postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: database_username
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: blog-secret
              key: database_password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: blog-configmap
              key: database_name
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
